# Generated by Django 5.0.6 on 2024-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemon_appeared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='disappeared_at',
            field=models.DateTimeField(null=True),
        ),
    ]
