# Generated by Django 5.0.6 on 2024-06-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemonentity_attack_power_pokemonentity_defense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='defense',
            new_name='defence',
        ),
    ]
