# Generated by Django 5.0.6 on 2024-06-20 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_alter_pokemon_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='start_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
