# Generated by Django 5.0.6 on 2024-06-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_pokemon_start_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='start_form',
            new_name='previous_evolution',
        ),
    ]
