# Generated by Django 5.0.6 on 2024-06-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_alter_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default='покемон не указан', on_delete=django.db.models.deletion.CASCADE, related_name='pokemonsss', to='pokemon_entities.pokemon', verbose_name='Укажите покемона'),
        ),
    ]
