# Generated by Django 5.0.6 on 2024-06-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0025_alter_pokemonentity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='attack_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сила атаки'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='defence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='endurance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выносливость'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='health_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очки здоровья'),
        ),
    ]
